image: docker:stable
services:
  - docker:dind

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

stages:
  - build

build:
   stage: build
   script:
     - docker build -t kaminchu/code-server-on-docker:gitlab-build .
     - docker push kaminchu/code-server-on-docker:gitlab-build
   tags:
     - docker
